### ISSUE TITLE
Thank you 💚✌🏻

### ISSUE THREAD

**Issue by thecannabisapp** [space-code/validator#5]
Wanna say thank you for putting this API together. I come from a React web background, so using validators like Zod or Yup is pretty standard. Having a validator API to use with Swift will make my life-building forms a lot easier. 💚✌🏻

**Comment by ns-vasilev** [comment]
@chinesehemp Hi, thanks for your feedback. You're welcome. I'm glad to hear that you find the `validator` package helpful. The `validator` can indeed streamline the process of handling form validation, making it more convenient. 

If you'd like to suggest improvements or come up with new ideas to this project, feel free to open a pull request. ✌🏻
